name: CICD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run build task
        run: npm run build --if-present

      - name: Generating tarball
        run: cd dist && tar -czf ../artifact.tar.gz .

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: artifact.tar.gz
          TARGET: /usr/local/issc/temp
          SCRIPT_AFTER: |
            cd /usr/local/issc/temp
            tar -xf artifact.tar.gz
            rm artifact.tar.gz
            cd ../
            rm -rf ./backup/*
            mv ./dist/* ./backup/
            rm -rf ./dist/*
            mv ./temp/* ./dist/
